apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secret
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
