apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: hands-on
  destination:
    namespace: ingress-nginx
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: {{ .Values.source.repoUrl }}
    path: ingress-nginx
    targetRevision: main
