apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: hands-on
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: {{ .Values.source.repoUrl }}
    path: sealed-secrets
    targetRevision: main
